
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xnksearxurrcijtdtxpg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhua3NlYXJ4dXJyY2lqdGR0eHBnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxODA5ODEsImV4cCI6MjA1ODc1Njk4MX0.YyqfQvw5xBJSuG-e1VyEWNXp3eKNoxTbvus7UthhwPI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
